version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/home/frontend/frontend
    ports: 
      - 3000:3000
    expose:
      - 3000